---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Customize the kernel and system settings through SysCtl
# @fonts: http://docs.ansible.com/ansible/latest/modules/sysctl_module.html
#         https://coreos.com/os/docs/latest/other-settings.html#tuning-sysctl-parameters
#         https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-2/
#-------------------------------------------------------------#

# ISSUE NOTICE:
- name: "SUB TASK : [ apply-custom-sysctl.yml ]"
  debug:
    msg: "START: Customize the kernel and system settings through SysCtl..."

- name: "Copy configuration file of parameters from sysctl"
  copy:
    src: "/usr/lib/sysctl.d/baselayout.conf" # OR src: "./files/baselayout-overwrite.conf"
    dest: "/etc/sysctl.d/baselayout-overwrite.conf"
    remote_src: true
    force: true
    owner: root
    group: root
    mode: 0644

- name: "Combine system_sysctl_settings and system_sysctl_settings_merge (if defined)"
  set_fact:
    system_sysctl_settings: "{{ system_sysctl_settings | combine(system_sysctl_settings_merge | default({})) }}"

- name: "Sysctl settings"
  sysctl:
    name: "{{item}}"
    value: "{{system_sysctl_settings[item]}}"
    sysctl_file: "/etc/sysctl.d/baselayout-overwrite.conf"
    sysctl_set: true
    reload: false
  with_items:
    - "{{ system_sysctl_settings | list }}"
  when: (system_sysctl_settings | list | length > 0)

- name: "Restart service (sysctl)"
  service:
    name: systemd-sysctl
    state: restarted
  when: (system_sysctl_settings | list | length > 0)
