---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Default variables to be used in the (K8s Master) rule.
# @fonts: https://github.com/githubixx/ansible-role-kubernetes-controller
#-------------------------------------------------------------#

# Current operating system of the environment.
system_current: "{{ global_system | default('coreos') }}"
# Operating system supported by the Role.
system_support_centos: centos
system_support_ubuntu: ubuntu
system_support_coreos: coreos


# The directory from where to copy the Etcd certificates. 
etcd_ca_source_directory: "{{ '~/k8s/certs/etcd' | expanduser }}"
# The port the control plane componentes should connect to etcd cluster
etcd_client_port: "2379"
# The interface the etcd cluster is listening on
etcd_interface: "enp0s8"
# Determine name of the inventory host group
etcd_group_name: "cluster_etcd"
# The etcd certificates needed for the control plane componentes 
# to be able to connect to the etcd cluster.
# Client/Server TLS trusted CA key file/peer server TLS trusted CA file
etcd_ca_pem_file: "ca-etcd.pem"
# Peer server TLS cert file
etcd_cert_pem_file: "cert-etcd.pem"
# Peer server TLS key file
etcd_cert_key_pem_file: "cert-etcd-key.pem"


# The directory from where to copy the K8s certificates. 
k8s_ca_source_directory: "{{ '~/k8s/certs/kubernetes' | expanduser }}"

# The directory from where to copy the K8s kubeconfigs. 
k8s_configs_source_directory: "{{ '~/k8s/kubeconfigs' | expanduser }}"

# Kubernetes Version
k8s_version: "1.10.0"
# Total number of initial hosts(Master), active.
k8s_master_count_hosts: "1"
# The directory to store the K8s certificates and other configuration
k8s_conf_dir: "/var/lib/kubernetes"
# The directory to store the K8s binaries
k8s_bin_dir: "/opt/bin"
# The directory from services(k8s*.service) of systemd.
k8s_systemd_dir: "/etc/systemd/system"
# Directory of support files for system provisioning.
k8s_support_files_dir: "/support-files/kubernetes-v{{k8s_version}}"
# K8s control plane binaries to download
k8s_master_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl
# The interface on which the K8s services should listen on. As all cluster
# communication should use the PeerVPN interface the interface name is
# normally "tap0" or "peervpn0".
k8s_master_interface: "enp0s8"
# Name of the inventory host group.
k8s_master_group_name: "cluster_master"

# The apiserver certificates needed for the control plane componentes 
# to be able to connect to the apiserver cluster.
# Client/Server TLS trusted CA key file/peer server TLS trusted CA file
k8s_apiserver_ca_pem_file: "ca-k8s-apiserver.pem"
# Peer server TLS cert file
k8s_apiserver_cert_pem_file: "cert-k8s-apiserver.pem"
# Peer server TLS key file
k8s_apiserver_cert_key_pem_file: "cert-k8s-apiserver-key.pem"

# K8s API daemon settings (can be overriden or additional added by defining
# "k8s_apiserver_settings_merge")
k8s_apiserver_settings:
  "apiserver-count": "{{ k8s_master_count_hosts }}"
  "advertise-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "bind-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "insecure-bind-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "admission-control": "Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
  "allow-privileged": "true"
  "authorization-mode": "Node,RBAC"
  "audit-log-maxage": "30"
  "audit-log-maxbackup": "3"
  "audit-log-maxsize": "100"
  "audit-log-path": "/var/log/audit.log"
  "enable-swagger-ui": "true"
  "event-ttl": "1h"
  "kubelet-https": "true"
  "kubelet-preferred-address-types": "InternalIP,Hostname,ExternalIP" # "--kubelet-preferred-address-types" defaults to:
                                                                      # "Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP"
                                                                      # Needs to be changed to make "kubectl logs" and "kubectl exec" work.
  "runtime-config": "api/all"
  "service-cluster-ip-range": "10.32.0.0/16"
  "service-node-port-range": "30000-32767"
  "service-account-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_pem_file }}"
  "client-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_pem_file }}"
  "kubelet-certificate-authority": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_pem_file }}"
  "kubelet-client-certificate": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_pem_file }}"
  "kubelet-client-key": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_pem_file }}"
  "tls-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_pem_file }}"
  "tls-cert-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_pem_file }}"
  "tls-private-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_pem_file }}"
  "etcd-cafile": "{{ k8s_conf_dir }}/{{ etcd_ca_pem_file }}"
  "etcd-certfile": "{{ k8s_conf_dir }}/{{ etcd_cert_pem_file }}"
  "etcd-keyfile": "{{ k8s_conf_dir }}/{{ etcd_cert_key_pem_file }}"
  "experimental-encryption-provider-config": "{{ k8s_conf_dir }}/encryption-config.yaml"

k8s_apiserver_settings_merge: {}

# K8s controller manager settings (can be overriden or additional added by defining
# "k8s_controller_manager_settings_merge")
k8s_controller_manager_settings:
  "address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "master": "{{ 'http://' + hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address + ':8080' }}"
  "cluster-cidr": "10.200.0.0/16"
  "cluster-name": "kubernetes"
  "leader-elect": "true"
  "service-cluster-ip-range": "10.32.0.0/16"
  "service-account-private-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_pem_file }}"
  "cluster-signing-cert-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_pem_file }}"
  "cluster-signing-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_pem_file }}"
  "root-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_pem_file }}"

k8s_controller_manager_settings_merge: {}

# K8s scheduler settings (can be overriden or additional added by defining
# "k8s_scheduler_settings_merge")
k8s_scheduler_settings:
  "address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "master": "{{ 'http://' + hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address + ':8080' }}"
  "leader-elect": "true"

k8s_scheduler_settings_merge: {}

# To correct the error quoted in the links below:
# https://github.com/kubernetes/kubernetes/issues/27607
# https://github.com/coreos/prometheus-operator/issues/870
# https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
# https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-6/
k8s_controller_manager_settings_merge:
  "address": "0.0.0.0"
k8s_scheduler_settings_merge:
  "address": "0.0.0.0"
