---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Default variables to be used in the (K8s Worker) rule.
# @fonts: https://github.com/githubixx/ansible-role-kubernetes-worker
#         https://serverfault.com/questions/829796/replication-controller-not-found
#         https://stackoverflow.com/questions/39910852/minikube-got-stuck-when-creating-container/39914584#39914584
#         https://stackoverflow.com/questions/48190928/kubernetes-pod-remains-in-containercreating-status
#-------------------------------------------------------------#

# The directory from where to copy the K8s certificates. 
k8s_certs_source_directory: "{{ '~/k8s/certs/kubernetes' | expanduser }}"

# The directory from where to copy the K8s kubeconfigs. 
k8s_configs_source_directory: "{{ '~/k8s/kubeconfigs' | expanduser }}"

# The directory to store the K8s certificates and other configuration
k8s_conf_dir: "/var/lib/kubernetes"
# The directory to store the K8s binaries
k8s_bin_dir: "/opt/bin"
# K8s release
k8s_release: "1.10.0"
# The interface on which the K8s services should listen on. As all cluster
# communication should use the PeerVPN interface the interface name is
# normally "tap0" or "peervpn0".
k8s_worker_interface: "enp0s8"

# K8s worker binaries to download
k8s_worker_binaries:
  - kube-proxy
  - kubelet
  - kubectl

# Certificate/CA files for API server and kube-proxy
k8s_apiserver_ca_file: "kube-apiserver-ca.pem"
# Client/Server TLS trusted CA key file/peer server TLS trusted CA file
# Peer server TLS cert/key file
k8s_apiserver_cert_file: "kube-apiserver-cert.pem"
k8s_apiserver_cert_key_file: "kube-apiserver-cert-key.pem"
k8s_kube_proxy_cert_file: "kube-proxy-cert.pem"
k8s_kube_proxy_cert_key_file: "kube-proxy-cert-key.pem"
k8s_kubelet_worker_cert_file: "kubelet-{{hostvars[inventory_hostname]['ansible_hostname']}}-cert.pem"
k8s_kubelet_worker_cert_key_file: "kubelet-{{hostvars[inventory_hostname]['ansible_hostname']}}-cert-key.pem"

# CNI network plugin settings
k8s_cni_dir: "/opt/cni"
k8s_cni_bin_dir: "{{k8s_cni_dir}}/bin"
k8s_cni_conf_dir: "/etc/cni/net.d"
k8s_cni_plugin_version: "0.7.1"
# Download directory for archive files (CNI)
k8s_cni_download_dir: "/support-files/cni-plugins-v{{k8s_cni_plugin_version}}"

# Directory to store kubelet configuration
k8s_worker_kubelet_conf_dir: "/var/lib/kubelet"

# kubelet settings
k8s_worker_kubelet_settings:
  "address": "{{hostvars[inventory_hostname]['ansible_' + k8s_worker_interface].ipv4.address}}"
  "node-ip": "{{hostvars[inventory_hostname]['ansible_' + k8s_worker_interface].ipv4.address}}"
  "allow-privileged": "true"
  "cluster-domain": "cluster.local"
  "cluster-dns": "10.32.0.254"
  "container-runtime": "docker"
  "docker": "unix:///var/run/docker.sock"
  "enable-custom-metrics": "true"
  "image-pull-progress-deadline": "2m"
  "kubeconfig": "{{k8s_worker_kubelet_conf_dir}}/kubeconfig"
  "register-node": "true"
  "runtime-request-timeout": "10m"
  "tls-cert-file": "{{k8s_conf_dir}}/{{k8s_apiserver_cert_file}}"
  "tls-private-key-file": "{{k8s_conf_dir}}/{{k8s_apiserver_cert_key_file}}"
  "serialize-image-pulls": "false"
  "cadvisor-port": "4194" # port or "0" to disable
  "healthz-bind-address": "{{hostvars[inventory_hostname]['ansible_' + k8s_worker_interface].ipv4.address}}"
  "healthz-port": "10248"
  "cloud-provider": ""
  "fail-swap-on": "false"
  "network-plugin": "cni"
  "cni-conf-dir": "{{k8s_cni_conf_dir}}"
  "cni-bin-dir": "{{k8s_cni_bin_dir}}"

# Directroy to store kube-proxy configuration
k8s_worker_kubeproxy_conf_dir: "/var/lib/kube-proxy"

# kube-proxy settings
k8s_worker_kubeproxy_settings:
  "bind-address": "{{hostvars[inventory_hostname]['ansible_' + k8s_worker_interface].ipv4.address}}"
  "healthz-bind-address": "{{hostvars[inventory_hostname]['ansible_' + k8s_worker_interface].ipv4.address}}"
  "proxy-mode": "iptables"
  "cluster-cidr": "10.200.0.0/16"
  "masquerade-all": "true"
  "kubeconfig": "{{k8s_worker_kubeproxy_conf_dir}}/kubeconfig"
