---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Apply basic security settings such as: (User creation, Privileges, 
#         Settings in sysctl, sshd and iptables)
# @fonts: https://github.com/githubixx/ansible-role-harden-linux
#         https://www.linode.com/docs/security/firewalls/control-network-traffic-with-iptables/
#         https://www.digitalocean.com/community/tutorials/how-to-isolate-servers-within-a-private-network-using-iptables
#         https://www.booleanworld.com/depth-guide-iptables-linux-firewall/
#         https://medium.com/@jasonrigden/hardening-ssh-1bcb99cd4cef
#         https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-2/
#         http://docs.ansible.com/ansible/latest/modules/user_module.html
#         http://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
#         http://docs.ansible.com/ansible/latest/modules/sysctl_module.html
#         http://bencane.com/2012/09/17/iptables-linux-firewall-rules-for-a-basic-web-server/
#         http://engineering.invisionapp.com/post/coreos-system-logs/
#-------------------------------------------------------------#

# Print the current operating system and the supported systems in the role.
- name: "Output: View current system and supported systems by the role"
  debug:
    msg: "--Current System:[{{system_current}}] --System Supported:[{{system_support_centos}},{{system_support_ubuntu}},{{system_support_coreos}}]"

- name: "Create directory for services of the SystemD"
  file:
    path: "{{security_systemd_dir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

# IpTables for (IPv4) - Settings.
- import_tasks: config-ip4table.yml
  when: 
    - (security_ip4tables_enable == true)
    - (system_current == system_support_centos) or
      (system_current == system_support_ubuntu) or 
      (system_current == system_support_coreos)
  
# IpTables for (IPv6) - Settings.
- import_tasks: config-ip6table.yml
  when: 
    - (security_ip6tables_enable == true)
    - (system_current == system_support_centos) or
      (system_current == system_support_ubuntu) or 
      (system_current == system_support_coreos)
