---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: 
# @fonts: 
#-------------------------------------------------------------

- name: "Create the admin user(kubectl) key CSR file"
  template:
    src: "ca-kubectl-cert-csr.json.j2"
    dest: "{{k8s_ca_source_directory}}/ca-kubectl-cert-csr.json"

- name: "Generate TLS certificate for admin user(kubectl)"
  shell: | 
    cfssl gencert \
          -ca=ca-kube-apiserver.pem \
          -ca-key=ca-kube-apiserver-key.pem \
          -config=ca-kube-apiserver-config.json \
          -profile=kubernetes ca-kubectl-cert-csr.json | cfssljson -bare ca-kubectl-cert
  args:
    chdir: "{{k8s_ca_source_directory}}"
    creates: "{{k8s_ca_source_directory}}/ca-kubectl-cert-key.pem"
