---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: 
# @fonts: 
#-------------------------------------------------------------#

- name: "Create the kube-proxy key CSR file"
  template:
    src: "../templates/cert-proxy-csr.json.j2"
    dest: "{{k8s_ca_source_directory}}/{{ k8s_ca_proxy_files_name.cert_csr_json }}.json"

- name: "Generate TLS certificate for kube-proxy"
  shell: | 
    cfssl gencert \
          -ca={{ k8s_ca_apiserver_files_name.ca_pem }}.pem \
          -ca-key={{ k8s_ca_apiserver_files_name.ca_key_pem }}.pem \
          -config={{ k8s_ca_apiserver_files_name.ca_config_json }}.json \
          -profile=kubernetes {{ k8s_ca_proxy_files_name.cert_csr_json }}.json | cfssljson -bare {{ k8s_ca_proxy_files_name.cert_pem }}
  args:
    chdir: "{{k8s_ca_source_directory}}"
    creates: "{{k8s_ca_source_directory}}/{{ k8s_ca_proxy_files_name.cert_key_pem }}.pem"
