---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Default variables to be used in the (K8s Master) rule.
# @fonts: https://github.com/githubixx/ansible-role-kubernetes-controller
#-------------------------------------------------------------#

# The directory from where to copy the Etcd certificates. 
etcd_certs_source_directory: "{{ '~/k8s/certs/etcd' | expanduser }}"

# The directory from where to copy the K8s certificates. 
k8s_certs_source_directory: "{{ '~/k8s/certs/kubernetes' | expanduser }}"

# The directory from where to copy the K8s kubeconfigs. 
k8s_configs_source_directory: "{{ '~/k8s/kubeconfigs' | expanduser }}"

# Total number of hosts(Master), active.
k8s_master_count_hosts: "1"
# The directory to store the K8s certificates and other configuration
k8s_conf_dir: "/var/lib/kubernetes"
# The directory to store the K8s binaries
k8s_bin_dir: "/opt/bin"
# K8s release
k8s_version: "1.10.0"
# K8s control plane binaries to download
k8s_controller_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl
# The interface on which the K8s services should listen on. As all cluster
# communication should use the PeerVPN interface the interface name is
# normally "tap0" or "peervpn0".
k8s_master_interface: "enp0s8"

# The port the control plane componentes should connect to etcd cluster
etcd_client_port: "2379"
# The interface the etcd cluster is listening on
etcd_interface: "enp0s8"
# The etcd certificates needed for the control plane componentes to be able
# to connect to the etcd cluster.
# Client/Server TLS trusted CA key file/peer server TLS trusted CA file
etcd_ca_file: "etcd-ca.pem"
# Peer server TLS cert file
etcd_cert_file: "etcd-cert.pem"
# Peer server TLS key file
etcd_cert_key_file: "etcd-cert-key.pem"

# K8s API daemon certificates
# Client/Server TLS trusted CA key file/peer server TLS trusted CA file
k8s_apiserver_ca_file: "kube-apiserver-ca.pem"
# Peer server TLS cert file
k8s_apiserver_cert_file: "kube-apiserver-cert.pem"
# Peer server TLS key file
k8s_apiserver_cert_key_file: "kube-apiserver-cert-key.pem"

# The directory from services(k8s*.service) of systemd.
k8s_systemd_service_dir: "/etc/systemd/system"
# K8s API daemon settings (can be overriden or additional added by defining
# "k8s_apiserver_settings_user")
k8s_apiserver_settings:
  "apiserver-count": "{{ k8s_master_count_hosts }}"
  "advertise-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "bind-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "insecure-bind-address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "admission-control": "Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
  "allow-privileged": "true"
  "authorization-mode": "Node,RBAC"
  "audit-log-maxage": "30"
  "audit-log-maxbackup": "3"
  "audit-log-maxsize": "100"
  "audit-log-path": "/var/log/audit.log"
  "enable-swagger-ui": "true"
  "event-ttl": "1h"
  "kubelet-https": "true"
  "kubelet-preferred-address-types": "InternalIP,Hostname,ExternalIP" # "--kubelet-preferred-address-types" defaults to:
                                                                      # "Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP"
                                                                      # Needs to be changed to make "kubectl logs" and "kubectl exec" work.
  "runtime-config": "api/all"
  "service-cluster-ip-range": "10.32.0.0/16"
  "service-node-port-range": "30000-32767"
  "service-account-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_file }}"
  "client-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_file }}"
  "kubelet-certificate-authority": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_file }}"
  "kubelet-client-certificate": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_file }}"
  "kubelet-client-key": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_file }}"
  "tls-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_file }}"
  "tls-cert-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_file }}"
  "tls-private-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_file }}"
  "etcd-cafile": "{{ k8s_conf_dir }}/{{ etcd_ca_file }}"
  "etcd-certfile": "{{ k8s_conf_dir }}/{{ etcd_cert_file }}"
  "etcd-keyfile": "{{ k8s_conf_dir }}/{{ etcd_cert_key_file }}"
  "experimental-encryption-provider-config": "{{ k8s_conf_dir }}/encryption-config.yaml"

# K8s controller manager settings (can be overriden or additional added by defining
# "k8s_controller_manager_settings_user")
k8s_controller_manager_settings:
  "address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "master": "{{ 'http://' + hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address + ':8080' }}"
  "cluster-cidr": "10.200.0.0/16"
  "cluster-name": "kubernetes"
  "leader-elect": "true"
  "service-cluster-ip-range": "10.32.0.0/16"
  "service-account-private-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_file }}"
  "cluster-signing-cert-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_file }}"
  "cluster-signing-key-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_cert_key_file }}"
  "root-ca-file": "{{ k8s_conf_dir }}/{{ k8s_apiserver_ca_file }}"

# kube-scheduler settings
k8s_scheduler_settings:
  "address": "{{ hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address }}"
  "master": "{{ 'http://' + hostvars[inventory_hostname]['ansible_' + k8s_master_interface].ipv4.address + ':8080' }}"
  "leader-elect": "true"

# To correct the error quoted in the links below:
# https://github.com/kubernetes/kubernetes/issues/27607
# https://github.com/coreos/prometheus-operator/issues/870
# https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
# https://www.tauceti.blog/post/kubernetes-the-not-so-hard-way-with-ansible-at-scaleway-part-6/
k8s_controller_manager_settings_user:
  "address": "0.0.0.0"
k8s_scheduler_settings_user:
  "address": "0.0.0.0"
