---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Installs Docker from official Docker binaries archive. 
#         For managing Docker daemon systemd is used.
# @fonts: https://github.com/githubixx/ansible-role-docker
#         https://coreos.com/os/docs/latest/getting-started-with-docker.html
#-------------------------------------------------------------#

- name: "Create docker-tcp.socket systemd file"
  template:
    src: "./templates/docker-tcp.socket.j2"
    dest: "/etc/systemd/system/docker-tcp.socket"
    owner: root
    group: root
    mode: 0644

- name: "Enable and start docker-tcp.socket"
  systemd:
    daemon_reload: yes
    name: docker-tcp.socket
    enabled: yes
    state: started
    no_block: yes

- name: "Enable and start Docker"
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started
    no_block: yes
