---

# Print the current operating system and the supported systems in the role.
- name: "Output: View current system and supported systems by the role"
  debug:
    msg: "--Current System:[{{system_current}}] --System Supported:[{{system_support_centos}},{{system_support_ubuntu}},{{system_support_coreos}}]"

- name: "WARNING: Configuration not implemented!!!"
  debug:
    msg: "OUTPUT: {{hostvars[inventory_hostname]['ansible_hostname']}} - {{hostvars[inventory_hostname]['ansible_host']}}"
