---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Configure remote access security through SSHD
# @fonts: 
#-------------------------------------------------------------#

# ISSUE NOTICE:
- name: "SUB TASK : [ config-sshd.yml ]"
  debug:
    msg: "START: Configure remote access security through SSHD..."

- name: "Copy ssh service configuration file"
  copy:
    src: "../files/sshd_config"
    dest: "/etc/ssh/sshd_config"
    backup: true
    force: false
    owner: root
    group: root
    mode: 0600

- name: "Combine security_sshd_settings and security_sshd_settings_merge (if defined)"
  set_fact:
    security_sshd_settings: "{{ security_sshd_settings | combine(security_sshd_settings_merge | default({})) }}"

- name: "Output: Variable (security_sshd_settings)"
  debug:
    var=security_sshd_settings

- name: "Ensure sshd_config setting"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item }}"
    line: "{{ security_sshd_settings[item] }}"
    state: "present"
  with_items:
    - "{{ security_sshd_settings | list }}"
  when: (security_sshd_settings | list | length > 0)

- name: "Restart service (sshd)"
  service:
    name: sshd
    state: restarted
  ignore_errors: true
  when: (security_sshd_settings | list | length > 0)
