---
#-----------------------|DOCUMENTATION|-----------------------#
# @descr: Ansible role which adds /etc/environment variables.
# @fonts: https://github.com/weareinteractive/ansible-environment
#-------------------------------------------------------------#

# Print the current operating system and the supported systems in the role.
- name: "Output: View current system and supported systems by the role"
  debug:
    msg: "--Current System:[{{system_current}}] --System Supported:[{{system_support_centos}},{{system_support_ubuntu}},{{system_support_coreos}}]"

- name: "Ensure file exists"
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

- name: "Remove previous values"
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key }}\ ?='
    state: absent
  with_dict: "{{ environment_config }}"

- name: "Configuring environment"
  lineinfile:
    dest: "{{ environment_file }}"
    line: "{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ environment_config }}"
